.Dd September 21, 2011
.Dt TVIEWER 1
.Sh NAME
.Nm tviewer 
.Nd MMTK trajectory viewer
.Sh SYNOPSIS
.Nm
.Ar trajectory_file
.Sh DESCRIPTION
tviewer plots energies and thermodynamic quantities stored in an
MMTK trajectory. It can also extract configurations in PDB format
and run a visualization program to display an animation.
.Pp
