/* Generated by Pyrex 0.9.4.1 on Thu Jan 11 11:30:22 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "MMTK/arrayobject.h"
#include "MMTK/core.h"
#include "MMTK/universe.h"
#include "MMTK/forcefield.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

/* Declarations from MMTK_energy_term */


struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm {
  PyFFEnergyTermObject __pyx_base;
  struct __pyx_vtabstruct_16MMTK_energy_term_PyEnergyTerm *__pyx_vtab;
  PyObject *universe;
  PyObject *configuration;
};

struct __pyx_vtabstruct_16MMTK_energy_term_PyEnergyTerm {
  void ((*c_evaluate)(struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *,PyFFEvaluatorObject *,energy_spec (*),energy_data (*)));
};
static struct __pyx_vtabstruct_16MMTK_energy_term_PyEnergyTerm *__pyx_vtabptr_16MMTK_energy_term_PyEnergyTerm;

static PyTypeObject *__pyx_ptype_16MMTK_energy_term_ArrayType = 0;
static PyTypeObject *__pyx_ptype_16MMTK_energy_term_EnergyTerm = 0;
static PyTypeObject *__pyx_ptype_16MMTK_energy_term_EnergyEvaluator = 0;
static PyTypeObject *__pyx_ptype_16MMTK_energy_term_PyEnergyTerm = 0;

/* Implementation of MMTK_energy_term */


static PyObject *__pyx_n_MMTK;
static PyObject *__pyx_n_N;
static PyObject *__pyx_n_Scientific;

static PyObject *__pyx_n___init__;

static int __pyx_f_16MMTK_energy_term_12PyEnergyTerm___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_16MMTK_energy_term_12PyEnergyTerm___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_name = 0;
  PyObject *__pyx_v_universe = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"name","universe",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_name, &__pyx_v_universe)) return -1;
  Py_INCREF((PyObject *)__pyx_v_self);
  Py_INCREF(__pyx_v_name);
  Py_INCREF(__pyx_v_universe);

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":18 */
  __pyx_1 = PyObject_GetAttr(((PyObject*)__pyx_ptype_16MMTK_energy_term_EnergyTerm), __pyx_n___init__); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_INCREF(__pyx_v_name);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_name);
  __pyx_3 = PyTuple_New(4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_self);
  Py_INCREF(__pyx_v_universe);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_universe);
  Py_INCREF(__pyx_v_name);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_v_name);
  PyTuple_SET_ITEM(__pyx_3, 3, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":19 */
  ((struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->__pyx_base.eval_func = ((void (*))__pyx_vtabptr_16MMTK_energy_term_PyEnergyTerm->c_evaluate);

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":20 */
  Py_INCREF(__pyx_v_universe);
  Py_DECREF(((struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->universe);
  ((struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->universe = __pyx_v_universe;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":21 */
  Py_INCREF(Py_None);
  Py_DECREF(((struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->configuration);
  ((struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->configuration = Py_None;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("MMTK_energy_term.PyEnergyTerm.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_universe);
  return __pyx_r;
}

static PyObject *__pyx_n_name;
static PyObject *__pyx_n_term_names;
static PyObject *__pyx_n_range;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_tuple;
static PyObject *__pyx_n_AttributeError;


static PyObject *__pyx_f_16MMTK_energy_term_12PyEnergyTerm___getattr__(PyObject *__pyx_v_self, PyObject *__pyx_v_name); /*proto*/
static PyObject *__pyx_f_16MMTK_energy_term_12PyEnergyTerm___getattr__(PyObject *__pyx_v_self, PyObject *__pyx_v_name) {
  PyObject *__pyx_v_names;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  Py_INCREF(__pyx_v_name);
  __pyx_v_names = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":24 */
  if (PyObject_Cmp(__pyx_v_name, __pyx_n_name, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":25 */
    __pyx_2 = PyString_FromString(((struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->__pyx_base.evaluator_name); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  if (PyObject_Cmp(__pyx_v_name, __pyx_n_term_names, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  if (__pyx_1) {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":27 */
    __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
    Py_DECREF(__pyx_v_names);
    __pyx_v_names = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":28 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(((struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->__pyx_base.nterms); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    for (;;) {
      __pyx_L3:;
      __pyx_4 = PyIter_Next(__pyx_2);
      if (!__pyx_4) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_i);
      __pyx_v_i = __pyx_4;
      __pyx_4 = 0;

      /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":29 */
      __pyx_3 = PyObject_GetAttr(__pyx_v_names, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
      __pyx_1 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
      __pyx_4 = PyString_FromString((((struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)__pyx_v_self)->__pyx_base.term_names[__pyx_1])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
      __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_4);
      __pyx_4 = 0;
      __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
    }
    __pyx_L4:;
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":30 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_tuple); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_INCREF(__pyx_v_names);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_names);
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_r = __pyx_4;
    __pyx_4 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":32 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_AttributeError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_v_name, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("MMTK_energy_term.PyEnergyTerm.__getattr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_names);
  Py_DECREF(__pyx_v_i);
  Py_DECREF((PyObject *)__pyx_v_self);
  Py_DECREF(__pyx_v_name);
  return __pyx_r;
}

static PyObject *__pyx_n_Configuration;
static PyObject *__pyx_n_array;
static PyObject *__pyx_n_evaluate;
static PyObject *__pyx_n_energy;
static PyObject *__pyx_n_virial;
static PyObject *__pyx_n_KeyError;
static PyObject *__pyx_n_add;
static PyObject *__pyx_n_gradients;
static PyObject *__pyx_n_force_constants;


static void __pyx_f_16MMTK_energy_term_12PyEnergyTerm_c_evaluate(struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *__pyx_v_self,PyFFEvaluatorObject *__pyx_v_eval,energy_spec (*__pyx_v_input),energy_data (*__pyx_v_energy)) {
  int __pyx_v_do_gradients;
  int __pyx_v_do_fc;
  PyObject *__pyx_v_energy_dict;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  double __pyx_6;
  PyObject *__pyx_7 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  Py_INCREF(__pyx_v_eval);
  __pyx_v_energy_dict = Py_None; Py_INCREF(Py_None);

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":37 */
  __pyx_v_do_gradients = (__pyx_v_energy->gradients != 0);

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":38 */
  __pyx_v_do_fc = (__pyx_v_energy->force_constants != 0);

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":39 */
  __pyx_1 = __pyx_v_self->configuration == Py_None;
  if (__pyx_1) {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":40 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_MMTK); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_Configuration); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = (PyObject *)__pyx_v_input->coordinates;
    Py_INCREF(__pyx_2);
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    Py_INCREF(__pyx_v_self->universe);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_self->universe);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_self->configuration);
    __pyx_v_self->configuration = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":43 */
    __pyx_3 = (PyObject *)__pyx_v_input->coordinates;
    Py_INCREF(__pyx_3);
    if (PyObject_SetAttr(__pyx_v_self->configuration, __pyx_n_array, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  __pyx_L2:;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":44 */
  /*try:*/ {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":45 */
    __pyx_4 = PyObject_GetAttr(((PyObject *)__pyx_v_self), __pyx_n_evaluate); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L3;}
    __pyx_2 = PyInt_FromLong(__pyx_v_do_gradients); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L3;}
    __pyx_3 = PyInt_FromLong(__pyx_v_do_fc); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L3;}
    __pyx_5 = PyTuple_New(3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L3;}
    Py_INCREF(__pyx_v_self->configuration);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_self->configuration);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
    PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyObject_CallObject(__pyx_4, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L3;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_v_energy_dict);
    __pyx_v_energy_dict = __pyx_2;
    __pyx_2 = 0;
  }
  goto __pyx_L4;
  __pyx_L3:;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_5); __pyx_5 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":47 */
  /*except:*/ {
    __Pyx_AddTraceback("MMTK_energy_term.c_evaluate");
    __pyx_3 = __Pyx_GetExcValue(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":48 */
    __pyx_v_energy->error = 1;

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":49 */
    __Pyx_ReRaise();
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":50 */
  __pyx_4 = PyObject_GetItem(__pyx_v_energy_dict, __pyx_n_energy); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_6 = PyFloat_AsDouble(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  (__pyx_v_energy->energy_terms[__pyx_v_self->__pyx_base.index]) = __pyx_6;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":51 */
  /*try:*/ {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":53 */
    __pyx_5 = PyFloat_FromDouble((__pyx_v_energy->energy_terms[__pyx_v_self->__pyx_base.virial_index])); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L5;}
    __pyx_2 = PyObject_GetItem(__pyx_v_energy_dict, __pyx_n_virial); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L5;}
    __pyx_3 = PyNumber_Add(__pyx_5, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L5;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_6 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L5;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    (__pyx_v_energy->energy_terms[__pyx_v_self->__pyx_base.virial_index]) = __pyx_6;
  }
  goto __pyx_L6;
  __pyx_L5:;
  Py_XDECREF(__pyx_4); __pyx_4 = 0;
  Py_XDECREF(__pyx_5); __pyx_5 = 0;
  Py_XDECREF(__pyx_2); __pyx_2 = 0;
  Py_XDECREF(__pyx_3); __pyx_3 = 0;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":54 */
  __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_KeyError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_1 = PyErr_ExceptionMatches(__pyx_4);
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__pyx_1) {
    __Pyx_AddTraceback("MMTK_energy_term.c_evaluate");
    __pyx_5 = __Pyx_GetExcValue(); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":55 */
    __pyx_v_energy->virial_available = 0;
    goto __pyx_L6;
  }
  goto __pyx_L1;
  __pyx_L6:;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":56 */
  __pyx_1 = __pyx_v_do_gradients;
  if (__pyx_1) {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":57 */
    /*try:*/ {

      /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":58 */
      __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_N); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L8;}
      __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_add); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L8;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_4 = (PyObject *)__pyx_v_energy->gradients;
      Py_INCREF(__pyx_4);
      __pyx_5 = PyObject_GetItem(__pyx_v_energy_dict, __pyx_n_gradients); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L8;}
      __pyx_2 = PyObject_GetAttr(__pyx_5, __pyx_n_array); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L8;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_5 = (PyObject *)__pyx_v_energy->gradients;
      Py_INCREF(__pyx_5);
      __pyx_7 = PyTuple_New(3); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L8;}
      PyTuple_SET_ITEM(__pyx_7, 0, __pyx_4);
      PyTuple_SET_ITEM(__pyx_7, 1, __pyx_2);
      PyTuple_SET_ITEM(__pyx_7, 2, __pyx_5);
      __pyx_4 = 0;
      __pyx_2 = 0;
      __pyx_5 = 0;
      __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_7); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L8;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
    }
    goto __pyx_L9;
    __pyx_L8:;
    Py_XDECREF(__pyx_2); __pyx_2 = 0;
    Py_XDECREF(__pyx_5); __pyx_5 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_7); __pyx_7 = 0;
    Py_XDECREF(__pyx_4); __pyx_4 = 0;

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":61 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_KeyError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
    __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_AttributeError); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
    __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_3, 1, __pyx_5);
    __pyx_2 = 0;
    __pyx_5 = 0;
    __pyx_1 = PyErr_ExceptionMatches(__pyx_3);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (__pyx_1) {
      __Pyx_AddTraceback("MMTK_energy_term.c_evaluate");
      __pyx_7 = __Pyx_GetExcValue(); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;

      /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":62 */
      __pyx_v_energy->error = 1;

      /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":63 */
      __Pyx_ReRaise();
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
      goto __pyx_L9;
    }
    goto __pyx_L1;
    __pyx_L9:;
    goto __pyx_L7;
  }
  __pyx_L7:;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":64 */
  __pyx_1 = __pyx_v_do_fc;
  if (__pyx_1) {

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":65 */
    /*try:*/ {

      /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":66 */
      __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_N); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L11;}
      __pyx_2 = PyObject_GetAttr(__pyx_4, __pyx_n_add); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L11;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_5 = (PyObject *)__pyx_v_energy->force_constants;
      Py_INCREF(__pyx_5);
      __pyx_3 = PyObject_GetItem(__pyx_v_energy_dict, __pyx_n_force_constants); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L11;}
      __pyx_7 = PyObject_GetAttr(__pyx_3, __pyx_n_array); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L11;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_4 = (PyObject *)__pyx_v_energy->force_constants;
      Py_INCREF(__pyx_4);
      __pyx_3 = PyTuple_New(3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L11;}
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_5);
      PyTuple_SET_ITEM(__pyx_3, 1, __pyx_7);
      PyTuple_SET_ITEM(__pyx_3, 2, __pyx_4);
      __pyx_5 = 0;
      __pyx_7 = 0;
      __pyx_4 = 0;
      __pyx_5 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L11;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
    }
    goto __pyx_L12;
    __pyx_L11:;
    Py_XDECREF(__pyx_7); __pyx_7 = 0;
    Py_XDECREF(__pyx_4); __pyx_4 = 0;
    Py_XDECREF(__pyx_2); __pyx_2 = 0;
    Py_XDECREF(__pyx_3); __pyx_3 = 0;
    Py_XDECREF(__pyx_5); __pyx_5 = 0;

    /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":69 */
    __pyx_7 = __Pyx_GetName(__pyx_b, __pyx_n_KeyError); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
    __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_AttributeError); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_7);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_4);
    __pyx_7 = 0;
    __pyx_4 = 0;
    __pyx_1 = PyErr_ExceptionMatches(__pyx_2);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__pyx_1) {
      __Pyx_AddTraceback("MMTK_energy_term.c_evaluate");
      __pyx_3 = __Pyx_GetExcValue(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;

      /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":70 */
      __pyx_v_energy->error = 1;

      /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":71 */
      __Pyx_ReRaise();
      {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
      goto __pyx_L12;
    }
    goto __pyx_L1;
    __pyx_L12:;
    goto __pyx_L10;
  }
  __pyx_L10:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("MMTK_energy_term.PyEnergyTerm.c_evaluate");
  __pyx_L0:;
  Py_DECREF(__pyx_v_energy_dict);
  Py_DECREF((PyObject *)__pyx_v_self);
  Py_DECREF(__pyx_v_eval);
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_AttributeError, "AttributeError"},
  {&__pyx_n_Configuration, "Configuration"},
  {&__pyx_n_KeyError, "KeyError"},
  {&__pyx_n_MMTK, "MMTK"},
  {&__pyx_n_N, "N"},
  {&__pyx_n_Scientific, "Scientific"},
  {&__pyx_n___init__, "__init__"},
  {&__pyx_n_add, "add"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_array, "array"},
  {&__pyx_n_energy, "energy"},
  {&__pyx_n_evaluate, "evaluate"},
  {&__pyx_n_force_constants, "force_constants"},
  {&__pyx_n_gradients, "gradients"},
  {&__pyx_n_name, "name"},
  {&__pyx_n_range, "range"},
  {&__pyx_n_term_names, "term_names"},
  {&__pyx_n_tuple, "tuple"},
  {&__pyx_n_virial, "virial"},
  {0, 0}
};
static struct __pyx_vtabstruct_16MMTK_energy_term_PyEnergyTerm __pyx_vtable_16MMTK_energy_term_PyEnergyTerm;

static PyObject *__pyx_tp_new_16MMTK_energy_term_PyEnergyTerm(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_16MMTK_energy_term_EnergyTerm->tp_new(t, a, k);
  struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *p = (struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)o;
  *(struct __pyx_vtabstruct_16MMTK_energy_term_PyEnergyTerm **)&p->__pyx_vtab = __pyx_vtabptr_16MMTK_energy_term_PyEnergyTerm;
  p->universe = Py_None; Py_INCREF(Py_None);
  p->configuration = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_16MMTK_energy_term_PyEnergyTerm(PyObject *o) {
  struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *p = (struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)o;
  Py_XDECREF(p->universe);
  Py_XDECREF(p->configuration);
  __pyx_ptype_16MMTK_energy_term_EnergyTerm->tp_dealloc(o);
}

static int __pyx_tp_traverse_16MMTK_energy_term_PyEnergyTerm(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *p = (struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)o;
  e = __pyx_ptype_16MMTK_energy_term_EnergyTerm->tp_traverse(o, v, a); if (e) return e;
  if (p->universe) {
    e = (*v)(p->universe, a); if (e) return e;
  }
  if (p->configuration) {
    e = (*v)(p->configuration, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_16MMTK_energy_term_PyEnergyTerm(PyObject *o) {
  struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *p = (struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm *)o;
  __pyx_ptype_16MMTK_energy_term_EnergyTerm->tp_clear(o);
  Py_XDECREF(p->universe);
  p->universe = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->configuration);
  p->configuration = Py_None; Py_INCREF(Py_None);
  return 0;
}

static PyObject *__pyx_tp_getattro_16MMTK_energy_term_PyEnergyTerm(PyObject *o, PyObject *n) {
  PyObject *v = PyObject_GenericGetAttr(o, n);
  if (!v && PyErr_ExceptionMatches(PyExc_AttributeError)) {
    PyErr_Clear();
    v = __pyx_f_16MMTK_energy_term_12PyEnergyTerm___getattr__(o, n);
  }
  return v;
}

static struct PyMethodDef __pyx_methods_16MMTK_energy_term_PyEnergyTerm[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_16MMTK_energy_term_PyEnergyTerm[] = {
  {"universe", T_OBJECT, offsetof(struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm, universe), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_PyEnergyTerm = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_PyEnergyTerm = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_PyEnergyTerm = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_PyEnergyTerm = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_16MMTK_energy_term_PyEnergyTerm = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "MMTK_energy_term.PyEnergyTerm", /*tp_name*/
  sizeof(struct __pyx_obj_16MMTK_energy_term_PyEnergyTerm), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_16MMTK_energy_term_PyEnergyTerm, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_PyEnergyTerm, /*tp_as_number*/
  &__pyx_tp_as_sequence_PyEnergyTerm, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_PyEnergyTerm, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  __pyx_tp_getattro_16MMTK_energy_term_PyEnergyTerm, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_PyEnergyTerm, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_16MMTK_energy_term_PyEnergyTerm, /*tp_traverse*/
  __pyx_tp_clear_16MMTK_energy_term_PyEnergyTerm, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_16MMTK_energy_term_PyEnergyTerm, /*tp_methods*/
  __pyx_members_16MMTK_energy_term_PyEnergyTerm, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_16MMTK_energy_term_12PyEnergyTerm___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_16MMTK_energy_term_PyEnergyTerm, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initMMTK_energy_term(void); /*proto*/
PyMODINIT_FUNC initMMTK_energy_term(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("MMTK_energy_term", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  __pyx_ptype_16MMTK_energy_term_ArrayType = __Pyx_ImportType("Scientific.N", "ArrayType", sizeof(PyArrayObject)); if (!__pyx_ptype_16MMTK_energy_term_ArrayType) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 27; goto __pyx_L1;}
  __pyx_ptype_16MMTK_energy_term_EnergyTerm = __Pyx_ImportType("MMTK_forcefield", "EnergyTerm", sizeof(PyFFEnergyTermObject)); if (!__pyx_ptype_16MMTK_energy_term_EnergyTerm) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_ptype_16MMTK_energy_term_EnergyEvaluator = __Pyx_ImportType("MMTK_forcefield", "EnergyEvaluator", sizeof(PyFFEvaluatorObject)); if (!__pyx_ptype_16MMTK_energy_term_EnergyEvaluator) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 80; goto __pyx_L1;}
  __pyx_vtabptr_16MMTK_energy_term_PyEnergyTerm = &__pyx_vtable_16MMTK_energy_term_PyEnergyTerm;
  *(void **)&__pyx_vtable_16MMTK_energy_term_PyEnergyTerm.c_evaluate = (void *)__pyx_f_16MMTK_energy_term_12PyEnergyTerm_c_evaluate;
  __pyx_type_16MMTK_energy_term_PyEnergyTerm.tp_base = __pyx_ptype_16MMTK_energy_term_EnergyTerm;
  __pyx_type_16MMTK_energy_term_PyEnergyTerm.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_16MMTK_energy_term_PyEnergyTerm) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_16MMTK_energy_term_PyEnergyTerm.tp_dict, __pyx_vtabptr_16MMTK_energy_term_PyEnergyTerm) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "PyEnergyTerm", (PyObject *)&__pyx_type_16MMTK_energy_term_PyEnergyTerm) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  __pyx_ptype_16MMTK_energy_term_PyEnergyTerm = &__pyx_type_16MMTK_energy_term_PyEnergyTerm;

  /* "../Include/MMTK/numeric.pxi":37 */
  import_array();

  /* "../Include/MMTK/forcefield.pxi":14 */
  import_MMTK_universe();

  /* "../Include/MMTK/forcefield.pxi":84 */
  import_MMTK_forcefield();

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":9 */
  __pyx_1 = __Pyx_Import(__pyx_n_MMTK, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MMTK, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":10 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_INCREF(__pyx_n_N);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_N);
  __pyx_2 = __Pyx_Import(__pyx_n_Scientific, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_N); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_N, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/hinsen/Programs/MMTK/main/Src/MMTK_energy_term.pyx":34 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("MMTK_energy_term");
}

static char *__pyx_filenames[] = {
  "MMTK_energy_term.pyx",
  "numeric.pxi",
  "forcefield.pxi",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static PyObject *__Pyx_GetExcValue(void) {
    PyObject *type = 0, *value = 0, *tb = 0;
    PyObject *result = 0;
    PyThreadState *tstate = PyThreadState_Get();
    PyErr_Fetch(&type, &value, &tb);
    PyErr_NormalizeException(&type, &value, &tb);
    if (PyErr_Occurred())
        goto bad;
    if (!value) {
        value = Py_None;
        Py_INCREF(value);
    }
    Py_XDECREF(tstate->exc_type);
    Py_XDECREF(tstate->exc_value);
    Py_XDECREF(tstate->exc_traceback);
    tstate->exc_type = type;
    tstate->exc_value = value;
    tstate->exc_traceback = tb;
    result = value;
    Py_XINCREF(result);
    type = 0;
    value = 0;
    tb = 0;
bad:
    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(tb);
    return result;
}

static void __Pyx_ReRaise(void) {
    PyThreadState *tstate = PyThreadState_Get();
    PyObject *type = tstate->exc_type;
    PyObject *value = tstate->exc_value;
    PyObject *tb = tstate->exc_traceback;
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    PyErr_Restore(type, value, tb);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, 
    long size) 
{
    PyObject *py_module_name = 0;
    PyObject *py_class_name = 0;
    PyObject *py_name_list = 0;
    PyObject *py_module = 0;
    PyObject *result = 0;
    
    py_module_name = PyString_FromString(module_name);
    if (!py_module_name)
        goto bad;
    py_class_name = PyString_FromString(class_name);
    if (!py_class_name)
        goto bad;
    py_name_list = PyList_New(1);
    if (!py_name_list)
        goto bad;
    Py_INCREF(py_class_name);
    if (PyList_SetItem(py_name_list, 0, py_class_name) < 0)
        goto bad;
    py_module = __Pyx_Import(py_module_name, py_name_list);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttr(py_module, py_class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    goto done;
bad:
    Py_XDECREF(result);
    result = 0;
done:
    Py_XDECREF(py_module_name);
    Py_XDECREF(py_class_name);
    Py_XDECREF(py_name_list);
    return (PyTypeObject *)result;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
